### ISSUE TITLE
Call #s Menu

### ISSUE THREAD

**Issue by nbdm1284** [michalgm/freedom_archives_admin#16]
This is great. One question, can we have any ability to escape out of menus once something has been selected? Like if someone chooses the wrong call # right now they're stuck with their decision or they have to delete and start the record from scratch. Perhaps this is an issue in other menus too, but I haven't noticed it yet?

**Comment by michalgm** [comment]
ok - I've added a blank option to the call number dropdown

**Comment by nbdm1284** [comment]
thanks, great.
