### ISSUE TITLE
Really Long Drop down menus

### ISSUE THREAD

**Issue by nbdm1284** [michalgm/freedom_archives_admin#17]
I talked to Claude about some of these drop down menus that are gonna get lengthy. I think like specifically the collection, format and generation menus. I think the collection menus is fine the way we have it, that list is super long. For format and generation, the way you currently have it is good, but claude would like (if the field is blank) the entire list to show up if left click but you do not type anything. So for generation, if they type B they the options containing "B" populate a list but if you just left clicked into the blank field, the entire list would show up? Is this too much? Not super super high on my priority list.

**Comment by michalgm** [comment]
Ok- this should be working now

**Comment by nbdm1284** [comment]
not yet working...

**Comment by michalgm** [comment]
does this seem fixed now?

**Comment by nbdm1284** [comment]
seems fixed now, thanks.
