### ISSUE TITLE
Keyword size

### ISSUE THREAD

**Issue by michalgm** [michalgm/freedom_archives_admin#2]
Size of the keywords-> can they be bigger? Can we control their size? Is there a limit to how many show up at once? So if I type 100 will 100 show up?

**Comment by michalgm** [comment]
OK - I believe I've increased the minimum font size. The limit to the # of keywords that appear is currently 30. Let me know if it seems like this issue is resolved

**Comment by nbdm1284** [comment]
looks good, i'll keep my eye out for anything that looks wierd
