### ISSUE TITLE
Two urls in subjects list

### ISSUE THREAD

**Issue by nbdm1284** [michalgm/freedom_archives_admin#22]
These two urls appear in the subjects list. System won't let me delete or edit them. 

http://freedomarchives.org/Documents/Finder/DOC513_scans/Assata_Shakur/513.Assata.Bulletin.April.10.1974.pdf

http://freedomarchives.org/Documents/Finder/DOC513_scans/Assata_Shakur/513.Assata.Bulletin.Feb.1.1974.pdf

**Comment by michalgm** [comment]
The delete button should work now. Let me know if it you still can't remove these

**Comment by nbdm1284** [comment]
this is fixed.
