### ISSUE TITLE
Duplicate Records Feature

### ISSUE THREAD

**Issue by nbdm1284** [michalgm/freedom_archives_admin#23]
Without messing with your process to locate and delete duplicate records, we need a function to duplicate records similar to in FilerMaker Pro. This will ensure consistency in metadata for records that are copies of each other but in different formats.

**Comment by michalgm** [comment]
ah - I misread your original email - you want to *duplicate* records,
not remove duplicates. so, basically, for an existing record, you'd like
a button to create a new copy of that record, duplicating all of it's
information, correct?
This shouldn't be hard to do, but part of me cringes at the idea of
duplicating information in the database. It seems like a better design
would be to have a single record for all the metadata, with a list of
physical representations of that data for the different formats. But
that would take a significant redesign, so for now I think I'll just go
with the easy fix.

**Comment by michalgm** [comment]
This should be fixed
