### ISSUE TITLE
Collection Search/Manage Collections (Zimbabwe example)

### ISSUE THREAD

**Issue by nbdm1284** [michalgm/freedom_archives_admin#29]
In an email I've attached three screen shots. The first is the Zimbabwe collection showing up correctly when typed into the quick search field. The second screen shot is typing Zimbabwe into the Collection search box and the search box recognizing the term. The third screen shot is of after I have selected Zimbabwe in the Collection search box but nothing comes up. I've noticed this happens consistently except for the 14 front page collections which do not have parent collections.

**Comment by michalgm** [comment]
FYI - I think you can just reply to these github emails with attachments 
to attach screenshots.

**Comment by michalgm** [comment]
Ah - I understand now. This is a feature, not a bug! The 'collection'
search on that filters for things that are a member of the selected
collection - it works the same on both the records page and the
collections page. If I search for 'africa liberation movements', it only
shows the collections under that collection, including zimbabwe. If you
want to search for a specific collection by name, use either the quick
search or add a filter.

**Comment by michalgm** [comment]
Does my explanation above satisfy this issue? Can we close it?

**Comment by nbdm1284** [comment]
yeah we're good.
