### ISSUE TITLE
csv upload again

### ISSUE THREAD

**Issue by nbdm1284** [michalgm/freedom_archives_admin#30]
hey hope all is well. was trying to upload a csv today, went through the longer new process of converting to txt, changing the language and converting back. Keep getting a blank column 18 error. Can't seem to find any characters in column 18 and column 17 (place of publication) is normally the last column we have any data in. Just wondering if this means something to you?  Thanks.

**Comment by nbdm1284** [comment]
sorry "blank column header 18" is the error message.

**Comment by michalgm** [comment]
could you attach the file that's giving you problems? Thanks!

**Comment by nbdm1284** [comment]
...
