### ISSUE TITLE
Duplicate Button

### ISSUE THREAD

**Issue by nbdm1284** [michalgm/freedom_archives_admin#32]
I know we had originally decided that we wanted a process to find and get rid of duplicates not to add duplicates. But now we do in fact want a button that duplicates all a record's metadata (except format but its ok if everything gets copied and we just have to manually change the format). This would mainly be used when we're digitizing a record and don't want to type all the data again.  

Could this button only be used by the admin accounts?  Thanks.

**Comment by michalgm** [comment]
This should be fixed. However, at some point we should talk about making it so a single record can have multiple formats, if the is the only difference between them. That would be a cleaner way to do it, and would make the search results less confusing.

**Comment by nbdm1284** [comment]
I agree.
